[tool.poetry]
name = "minearchy-bot"
version = "1.0.0"
description = "A simple Discord bot for the Lands of Minearchy Discord server."
authors = ["RGBCube", "The Lands of Minearchy team"]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = { version = "*", extras = ["speed"] }
jishaku = "*"
mcstatus = "*"
uvloop = "*"

[tool.poetry.dev-dependencies]
flynt = "*"
isort = "*"
unimport = "*"

[tool.poetry.scripts]
bot = "minearchy_bot.__main__:main"

[tool.black]
line-length = 100
preview = true

[tool.isort]
py_version = 310
add_imports = ["from __future__ import annotations"]
line_length = 100
profile = "black"
combine_as_imports = true
combine_star = true
