name: Lint

on:
  - pull_request
  - push

env:
  python-version: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install Unimport, Isort, Black, and Flynt
        run: pip install -U pip unimport isort black flynt

      - name: Run Unimport
        continue-on-error: true
        run: unimport ./ --ignore-init --gitignore -r

      - name: Run Isort
        run: |
          isort ./
          python ./.github/workflows/scripts/lint.py

      - name: Run Black
        run: black ./

      - name: Run Flynt
        run: flynt ./ -tc

      - name: Setup Git
        run: git config --global user.name "Automated Linter"

      - name: Push To GitHub
        continue-on-error: true
        run: |
          git pull
          git add ./
          git commit --amend
          git push
